---

  - name: Test Cisco ansible playbook 3
    hosts: cisco-routers
    gather_facts: false
    connection: local

    tasks:

      - name: Config with template
        ios_config:
          src: templates/config.txt
          provider: "{{ cli }}"
